"""Prometheus metrics for the review pipeline.

Defines counters/histograms and thin helper functions used to instrument the
review flow. Metrics are registered on the default Prometheus registry and are
exposed by the API's ``/metrics`` endpoint for scraping.
"""
from __future__ import annotations

import logging

from prometheus_client import Counter, Histogram

logger = logging.getLogger("ai-code-review-api.metrics")

review_jobs_total = Counter(
    "review_jobs_total",
    "Total number of review jobs started.",
)
review_jobs_success_total = Counter(
    "review_jobs_success_total",
    "Total number of review jobs that completed successfully.",
)
review_jobs_failed_total = Counter(
    "review_jobs_failed_total",
    "Total number of review jobs that failed.",
)
review_comments_generated_total = Counter(
    "review_comments_generated_total",
    "Total number of review comments generated by the LLM.",
)
review_comments_published_total = Counter(
    "review_comments_published_total",
    "Total number of review comments published to GitHub.",
)
review_pipeline_duration_seconds = Histogram(
    "review_pipeline_duration_seconds",
    "Duration of the review pipeline in seconds.",
)


def record_review_started() -> None:
    """Record that a review job has started."""
    review_jobs_total.inc()
    logger.info("metrics_recorded", extra={"event": "review_started"})


def record_review_success(
    comments_generated: int, comments_published: int
) -> None:
    """Record a successful review job and its comment counts."""
    review_jobs_success_total.inc()
    if comments_generated:
        review_comments_generated_total.inc(comments_generated)
    if comments_published:
        review_comments_published_total.inc(comments_published)
    logger.info(
        "metrics_recorded",
        extra={
            "event": "review_success",
            "comments_generated": comments_generated,
            "comments_published": comments_published,
        },
    )


def record_review_failure() -> None:
    """Record a failed review job."""
    review_jobs_failed_total.inc()
    logger.info("metrics_recorded", extra={"event": "review_failure"})


def record_review_duration(seconds: float) -> None:
    """Record the duration of a review pipeline run."""
    review_pipeline_duration_seconds.observe(seconds)
    logger.info(
        "metrics_recorded",
        extra={"event": "review_duration", "seconds": seconds},
    )
